name: Run Tests

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: actions/setup-springboot@v1
        
        with:
          springboot-version: 2.4.0
          -name: Run Tests
          run: mvn test
          